WEKA:
  AMD:
    '*':
      #WEKApod - R6615:
      LogicalProc: Enabled
      NumaNodesPerSocket: "1"
      PcieAspmL1: Disabled
      ProcCStates: Disabled
      ProcPwrPerf: MaxPerf
      ProcVirtualization: Disabled
      SysProfile: Custom
      WorkloadProfile: NotConfigured
      DeterminismSlider: PerfDeterminism
      DfCState: Disabled
      DfPstateFreqOptimizer: Disabled
      DfPstateLatencyOptimizer: Disabled
      PowerProfileSelect: MaxIOPerformanceMode
      BootMode: Uefi
      SecureBoot: Disabled
      SerialComm: OnConRedir

Dell Inc.:
  AMD:
    PowerEdge R6615:
      LogicalProc: Enabled
      NumaNodesPerSocket: "1"
      PcieAspmL1: Disabled
      ProcCStates: Disabled
      ProcPwrPerf: MaxPerf
      ProcVirtualization: Disabled
      SysProfile: Custom
      WorkloadProfile: NotConfigured
      DeterminismSlider: PerfDeterminism
      DfCState: Disabled
      DfPstateFreqOptimizer: Disabled
      DfPstateLatencyOptimizer: Disabled
      PowerProfileSelect: MaxIOPerformanceMode
      BootMode: Uefi
      SecureBoot: Disabled
      SerialComm: OnConRedir

  Intel:
    '*':
      WorkloadProfile: LowLatencyOptimizedProfile
      SysProfile: Custom
      ControlledTurbo: Enabled
      LogicalProc: Disabled
      MadtCoreEnumeration: Linear
      MemPatrolScrub: Disabled
      MonitorMwait: Disabled
      ProcCStates: Disabled
      ProcHwPrefetcher: Enabled
      ProcPwrPerf: MaxPerf
      ProcTurboMode: Enabled
      ProcVirtualization: Disabled
      ProcX2Apic: Disabled
      #SubNumaCluster: Disabled
      SubNumaCluster: 2-Way
      #PackageCStates: Disabled
      ProcC1E: Disabled
      SecureBoot: Disabled
      SriovGlobalEnable: Enabled
      EnergyPerformanceBias: MaxPower
      #WorkloadConfiguration: Balance
HPE:
  AMD:
    '*':
      ApplicationPowerBoost: Enabled
      DeterminismControl: DeterminismCtrlAuto
      NumaMemoryDomainsPerSocket: OneMemoryDomainPerSocket
      ProcAmdIoVt: Enabled
      Sriov: Enabled
      ThermalConfig: IncreasedCooling
      WorkloadProfile: GeneralThroughputCompute
      CStateEfficiencyMode: Disabled
      DataFabricCStateEnable: Disabled
      InfinityFabricPstate: P0
      MinProcIdlePower: NoCStates
      NumaGroupSizeOpt: Clustered
      PerformanceDeterminism: PerformanceDeterministic
      PowerRegulator: StaticHighPerf
      ProcSMT: Enabled
      ProcAmdIoVt: Disabled
      BootMode: Uefi
      SecureBootStatus: Disabled
  Intel:
    '*':
      IntelProcVtd: Disabled
      ThermalConfig: IncreasedCooling
      WorkloadProfile: I/OThroughput
      ProcHyperthreading: Enabled
Supermicro:
  AMD:
    '*':
      ACPISRATL3CacheAsNUMADomain: Disabled
      IOMMU: Disabled
      NUMANodesPerSocket: NPS1
      SMTControl: Enabled
      DFCstates: Disabled
      GlobalC_stateControl: Disabled
      DeterminismControl: Manual
      PowerProfileSelection: "Maximum IO Performance Mode"
  Intel:
    '*':
      EnhancedHaltState(C1E): Disabled
      HardwareP-States: Disabled
      Hyper-Threading[ALL]: Enabled
      PackageCState: Disabled
      SR-IOVSupport: Enabled
      SpeedStep(P-States): Disabled
      Intel\u00aeVTforDirectedI/O(VT-d): Disabled
Lenovo:
  AMD:
    '*':
      Secured_Core_IOMMU: Disabled
      Processors_P_state1: Disabled
      Processors_P_state2: Disabled
      Processors_GlobalC_stateControl: Disabled
      Processors_DeterminismSlider: Performance
      Processors_DFC_States: Disabled
      DevicesandIOPorts_IOMMU: Disabled
      Processors_SMTMode: Enabled
      Power_PCIePowerBrake: Disabled
      OperatingModes_ChooseOperatingMode: CustomMode
      LegacyBIOS_LegacyBIOS: Disabled
      Processors_SOCP_states: P0
